### DISCUSSION TITLE
Improve cli for managing dumps

### DISCUSSION THREAD

**Discussion by juchom** [meilisearch/product#396] [Feedback & Feature Proposal]
Yesterday I tried to upgrade a Meilisearch docker with the actual tooling and I think it needs some improvements.

It was the first time I tried it and the experience was not good. I was expecting it to work a bit like Postgres or SQL Server for exemple.

On my dev machines I use a very basic setup with docker like this :

```
  meilisearch:
    image: getmeili/meilisearch:${MEILISEARCH_VERSION}
    container_name: meilisearch
    ports:
      - "7700:7700"
    environment:
      - MEILI_NO_ANALYTICS=true
```

Right now, the only option to do a dump is sending a curl command to the api and to restore a dump is only possible at start-up using the `--import-dump` flag.

It would be great to improve the CLI with new flags or new commands so we can start our docker image with a basic setup.

And have commands we can run while Meilisearch is running like `ms_dump /dumps/ms.dump` and restore a dump like `ms_restore /dumps/ms.dump`.

Postgres has [pg_dump](https://www.postgresql.org/docs/14/app-pgdump.html) and [pg_restore](https://www.postgresql.org/docs/14/app-pgrestore.html)
